#!/bin/sh

set -eu

echo -e "\n### Enabling desktop environment services" >&2

if [[ ! -e ~/.local/opt/axiom ]]; then
    git clone git@github.com:lnqs/axiom.git ~/.local/opt/axiom
fi

systemctl --user enable hypridle.service
systemctl --user start hypridle.service

systemctl --user enable arch-update-notifier
systemctl --user start arch-update-notifier

systemctl --user enable axiom
systemctl --user start axiom
