#!/bin/sh

set -eu

echo -e "\n### Enabling desktop environment services" >&2

systemctl --user enable waybar.service
systemctl --user start waybar.service

systemctl --user enable hypridle.service
systemctl --user start hypridle.service

systemctl --user enable hyprpaper.service
systemctl --user start hyprpaper.service

systemctl --user enable swaync.service
systemctl --user start swaync.service
