#!/bin/sh

set -eu

echo -e "\n### Enabling desktop environment services" >&2

if [[ ! -e ~/.local/opt/axiom ]]; then
    git clone git@github.com:lnqs/axiom.git ~/.local/opt/axiom
fi

systemctl --user enable axiom
systemctl --user start axiom
